name: Non-Technical Request
description: Request for non-technical tasks (e.g., presentations, documents, calls, etc.)
labels: [non-technical, task]
body:
  - type: input
    id: title
    attributes:
      label: Task Title
      description: A clear title describing the task.
      placeholder: "[Non-Technical] Something to be done"

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Provide a detailed description of the task.

  - type: checkboxes
    id: categories
    attributes:
      label: Categories
      description: Select one or more categories this task belongs to.
      options:
        - label: Documentation (e.g., Prepare documentation for some functionality)
        - label: Marketing (e.g., Prepare presentation for market)
        - label: Communication (e.g., Contact partners, Lawyer)
        - label: Multimedia (e.g., Create video, Edit assets)
        - label: Brainstorm (e.g., Discuss something)
        - label: Research (e.g., Prepare information about something)
        - label: Organizational (e.g., Prepare space, invite someone)

  - type: dropdown
    id: size
    attributes:
      label: Size
      description: Estimated effort to complete the task.
      options:
        - XS (< 1h)
        - S (1h - 4h)
        - M (4h - 8h)
        - L (8h - 16h)
        - XL (16h - 24h)
        - WTF (24h+)

  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: Provide a deadline if applicable (e.g., 2025-04-01).
      placeholder: YYYY-MM-DD
